services:
  - type: web
    name: fig-api-core
    runtime: python
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -k uvicorn.workers.UvicornWorker app.main:app
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: ENVIRONMENT
        value: prod